version: '3.7'

services:
  store_db:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/12/main/
    environment:
      POSTGRES_PASSWORD: 1974
      POSTGRES_USER: storedb
      POSTGRES_DB: store_db
    ports:
      - 8001:5432

  django:
    container_name: store
    build:
      context: ./
      dockerfile: Dockerfile
    command:  bash -c "python manage.py migrate --noinput &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/Online_store
    ports:
      - 8000:5432
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - store_db
      - redis

  celery:
    build: ./
    command: celery -A store worker --loglevel=INFO
    volumes:
      - .:/usr/src/app
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis

  redis:
    image: redis

volumes:
  pg_data:

