FROM python:3.8

ENV PYTHONDONTWRITEBYTRCODE 1
ENV PYTHONBUFFERED 1

WORKDIR /home/PycharmProjects/Onlinestore

COPY ./req.txt /home/PycharmProjects/req.txt
RUN pip install -r /home/PycharmProjects/req.txt

COPY . /home/PycharmProjects/Onlinestore

EXPOSE 8000
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]