# Generated by Django 3.2.3 on 2021-07-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='2 Изображение товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='3 Изображение товара'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_page',
            field=models.BooleanField(default=False, verbose_name='Отображается на главной'),
        ),
    ]
